<?php

namespace App\Models;

use App\Traits\HasUuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class TaskNextStep extends Model
{
    use HasFactory, HasUuid;

    protected $fillable = [
        'task_id',
        'content',
        'ai_generated',
    ];

    protected $casts = [
        'ai_generated' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    /**
     * Get the task that owns the next step.
     */
    public function task(): BelongsTo
    {
        return $this->belongsTo(Task::class);
    }

    /**
     * Check if this next step was generated by AI.
     */
    public function isAiGenerated(): bool
    {
        return $this->ai_generated;
    }

    /**
     * Get the formatted content with HTML.
     */
    public function getFormattedContent(): string
    {
        return nl2br(htmlspecialchars($this->content));
    }

    /**
     * Get the time elapsed since the next step was created.
     */
    public function getTimeElapsed(): string
    {
        return $this->created_at->diffForHumans();
    }

    /**
     * Boot the model.
     */
    protected static function boot()
    {
        parent::boot();

        static::created(function ($nextStep) {
            // Create activity log
            ActivityLog::create([
                'user_id' => auth()->id(),
                'activity' => 'Added next step to task',
                'details' => json_encode([
                    'task_id' => $nextStep->task_id,
                    'next_step_id' => $nextStep->id,
                    'ai_generated' => $nextStep->ai_generated,
                ]),
            ]);

            // If this is an AI-generated next step, create a notification for task assignees
            if ($nextStep->ai_generated) {
                foreach ($nextStep->task->assignees as $assignee) {
                    Notification::create([
                        'user_id' => $assignee->id,
                        'message' => 'AI has suggested a new next step for your task',
                        'type' => 'ai_suggestion',
                    ]);
                }
            }
        });
    }
}
